<?php

// !! Generated by: vendor/jesseschalken/autoload-generator/bin/generate-autoload include.php --exclude vendor

spl_autoload_register(function ($class) {
    static $map = array (
  'JesseSchalken\\DeepClone' => 'DeepClone.php',
  'JesseSchalken\\DeepCloneTest\\A' => 'DeepCloneTest.php',
  'JesseSchalken\\DeepCloneTest\\A2' => 'DeepCloneTest.php',
  'JesseSchalken\\DeepCloneTest\\B' => 'DeepCloneTest.php',
  'JesseSchalken\\DeepCloneTest\\DeepCloneTest' => 'DeepCloneTest.php',
);

    if (isset($map[$class]))
        require_once __DIR__ . "/{$map[$class]}";
}, true, false);

require_once __DIR__ . '/functions.php';

