<?php

// !! Generated by: ../vendor/bin/generate-autoload ./include.php

spl_autoload_register(function ($class) {
    static $map = array (
  'MagicUtils\\CloneNotSupportedException' => 'exceptions.php',
  'MagicUtils\\DeepClone' => 'traits.php',
  'MagicUtils\\NoClone' => 'traits.php',
  'MagicUtils\\NoDynamicMethods' => 'traits.php',
  'MagicUtils\\NoDynamicProperties' => 'traits.php',
  'MagicUtils\\NoMagic' => 'traits.php',
  'MagicUtils\\NoSerialize' => 'traits.php',
  'MagicUtils\\SerializeNotSupportedException' => 'exceptions.php',
  'MagicUtils\\Test\\A' => 'test.php',
  'MagicUtils\\Test\\A2' => 'test.php',
  'MagicUtils\\Test\\A3' => 'test.php',
  'MagicUtils\\Test\\B' => 'test.php',
  'MagicUtils\\Test\\NotCloneable' => 'test.php',
  'MagicUtils\\Test\\NotSerializable' => 'test.php',
  'MagicUtils\\Test\\Test' => 'test.php',
  'MagicUtils\\UndefinedMethodException' => 'exceptions.php',
  'MagicUtils\\UndefinedPropertyException' => 'exceptions.php',
);

    if (isset($map[$class]))
        require_once __DIR__ . "/{$map[$class]}";
}, true, false);

require_once __DIR__ . '/functions.php';

